### ISSUE TITLE
Need dataset or embeddings to run the downstream tasks.

### ISSUE THREAD

**Issue by Rajjat** [slzhou-xy/HREP#1]
Hello,
I want to run your code. But the dataset is unavailable. Could you please upload the dataset so that I can run your code? I read in your README file that you are busy. Maybe it will be helpful if you share the embeddings only.
Thanks 
Rajjat

**Comment by slzhou-xy** [comment]
Thanks for your attention to our paper. I will upload the dataset in the next few days. 😊😊
